services:
  admin.repository.post:
    class: Blank\Bundle\AdminBundle\Entity\PostRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    public: true
    arguments: [BlankAdminBundle:Post]

  admin.post_svc.controller:
    class: Blank\Bundle\AdminBundle\Controller\PostServiceController
    arguments: ['@doctrine.orm.default_entity_manager', '@admin.repository.post']

  admin.post_plain.controller:
    class: Blank\Bundle\AdminBundle\Controller\PostController
