imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    # При конвертации тела запроса оставить имена свойств без борабогтки (_/lower/upper)
    jms_serializer.camel_case_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy

framework:
    request:
      formats:
        csv: ['text/csv']
        json: ['text/plain', '*/*']
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
      - BlankAdminBundle
      - JMSTwigJsBundle
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        uglifycss:
          bin: %kernel.root_dir%/../node_modules/.bin/uglifycss
        uglifyjs:
          bin: %kernel.root_dir%/../node_modules/.bin/uglifyjs
        #twig_js:
        #  resource: "%kernel.root_dir%/config/twigjs.xml"
        #  apply_to: "\.twig$"
        #yui_js: ~


        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
  dbal:
    default_connection:  default
    connections:
      default:
        driver:   pdo_sqlite
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        path:     "%database_path%"

      development:
        driver:   pdo_mysql
        host:     localhost
        port:     ~
        dbname:   smartgroup
        user:     smartgroup
        password: smartgroup
        charset:  UTF8

  orm:
    default_entity_manager: default
    entity_managers:
      default:
        connection: default
        naming_strategy: doctrine.orm.naming_strategy.default
        #auto_mapping: true
        mappings:
          BlankAdminBundle: ~
      development:
        #auto_mapping: true
        mappings:
          BlankAdminBundle: ~
        connection: development
    auto_generate_proxy_classes: "%kernel.debug%"



sensio_framework_extra:
    request: { converters: true, auto_convert: true }
    view:    { annotations: false }
    router:  { annotations: true }
    cache:       { annotations: true }
    security:    { annotations: true }
    psr_message: { enabled: false } # Defaults to true if the PSR-7 bridge is installed


# Юзает объект при конвертации тела запроса из базы даных по недостающим параметрам
services: # TODO: check
  jms_serializer.object_constructor:
    alias: jms_serializer.doctrine_object_constructor
    public: false


  assetic.filter.twig_js:
    alias: twig_js.assetic_filter

# FOSRest Configuration
fos_rest:
   serializer:
     serialize_null: false # Нужен для исключения параметров, отсутсвующи х в запросе
   body_converter:
     enabled: true
     validate: true
     validation_errors_argument: validationErrors
   param_fetcher_listener: true
   body_listener:
     enabled: true
     default_format: json
     decoders:
       json: fos_rest.decoder.jsontoform
       xml: fos_rest.decoder.xml
   #routing_loader:
   #  default_format: json
   #  include_format: false
   #format_listener:
   #  rules:
   #   - {  path: ^/, priorities: [json, html, text], fallback_format: json, prefer_extension: false }
   view:
     view_response_listener: force
     serialize_null: false
     formats:
       json: true
       xml: false
       html: true
     #templating_formats:
       #json: true
       #html: true
     mime_types:
       json: ['application/json', 'application/json;version=1.0', 'application/json;version=1.1']
       enabled: false
       service: null
       # 'txt'  => array('text/plain'), перекрывает действие действие fos_ret.fallback_format - поэтому обнуляем
       txt: ['']
     force_redirects:
       html: true

   allowed_methods_listener: true
   access_denied_listener:
       json: true
       xml: true
       html: true

#namespace Negotiation;
# /**
#  * @author William Durand <william.durand1@gmail.com>
#  */
# class FormatNegotiator extends Negotiator implements FormatNegotiatorInterface
# {
#     // https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Request.php
#     protected $formats = array(
#         'html' => array('text/html', 'application/xhtml+xml'),
#         'txt'  => array('text/plain'),
#         'js'   => array('application/javascript', 'application/x-javascript', 'text/javascript'),
#         'css'  => array('text/css'),
#         'json' => array('application/json', 'application/x-json'),
#         'jsonld' => array('application/ld+json'),
#         'xml'  => array('text/xml', 'application/xml', 'application/x-xml'),
#         'rdf'  => array('application/rdf+xml'),
#         'atom' => array('application/atom+xml'),
#         'rss'  => array('application/rss+xml'),
#     ); ...



# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
