<?php

namespace Blank\Bundle\AdminBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PostController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Blank\Bundle\AdminBundle\Controller\PostController();
        $refProperty = new \ReflectionProperty('Blank\\Bundle\\AdminBundle\\Controller\\PostController', 'em');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('doctrine.orm.default_entity_manager', 1));
        $refProperty = new \ReflectionProperty('Blank\\Bundle\\AdminBundle\\Controller\\PostController', 'post');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('admin.repository.post', 1));
        $refProperty = new \ReflectionProperty('Blank\\Bundle\\AdminBundle\\Controller\\PostController', 'templating');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('templating', 1));
        return $instance;
    }
}
